(()=>{
const $=id=>document.getElementById(id);
const views={home:$('homeView'),quiz:$('quizView'),result:$('resultView')};
const state={mode:'expert',length:20,index:0,session:[],current:null,answered:false,used:new Set(),categoryCounts:{},lastMode:'expert'};
const STORAGE='ksaSurgicalExpertStatsV3';
const letters=['A','B','C','D','E'];

function loadStats(){try{return JSON.parse(localStorage.getItem(STORAGE))||{answered:0,correct:0,wrongIds:[]}}catch{return{answered:0,correct:0,wrongIds:[]}}}
function saveStats(s){localStorage.setItem(STORAGE,JSON.stringify(s));}
function showView(name){Object.values(views).forEach(v=>v.classList.remove('active'));views[name].classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}
function shuffle(arr){return [...arr].sort(()=>Math.random()-.5);}
function updateHome(){const s=loadStats();$('bankCount').textContent=window.KSA_QUESTIONS.length;$('caseCount').textContent=window.KSA_QUESTIONS.filter(q=>q.case).length;$('statAnswered').textContent=s.answered||0;$('statAccuracy').textContent=s.answered?Math.round((s.correct/s.answered)*100)+'%':'—';$('statErrors').textContent=(s.wrongIds||[]).length;}
function start(mode){
 state.mode=mode;state.lastMode=mode;state.index=0;state.session=[];state.used=new Set();state.categoryCounts={};state.answered=false;
 const selectedLength=Number($('examLength').value);
 let pool=poolForMode(mode);
 if(mode==='quick')state.length=Math.min(10,pool.length);else if(mode==='cases')state.length=Math.min(selectedLength,pool.length);else if(mode==='errors')state.length=Math.min(selectedLength,pool.length);else state.length=Math.min(selectedLength,pool.length);
 if(mode==='errors'&&!pool.length){alert('Você ainda não possui questões erradas salvas. Faça um exame Expert primeiro.');return;}
 showView('quiz');nextQuestion();
}
function poolForMode(mode=state.mode){const s=loadStats();if(mode==='cases')return window.KSA_QUESTIONS.filter(q=>q.case);if(mode==='pharm')return window.KSA_QUESTIONS.filter(q=>/Medication|Pharm|Antidote|Anticoag|Insulin|Opioid/i.test(q.category));if(mode==='errors'){const ids=new Set(s.wrongIds||[]);return window.KSA_QUESTIONS.filter(q=>ids.has(q.id));}return window.KSA_QUESTIONS;}
function pickQuestion(){let pool=poolForMode().filter(q=>!state.used.has(q.id));if(!pool.length)return null;const minCount=Math.min(...pool.map(q=>state.categoryCounts[q.category]||0));const balanced=pool.filter(q=>(state.categoryCounts[q.category]||0)<=minCount+1);return shuffle(balanced)[0]||shuffle(pool)[0];}
function nextQuestion(){if(state.index>=state.length){finish();return;}const q=pickQuestion();if(!q){finish();return;}state.current=q;state.used.add(q.id);state.categoryCounts[q.category]=(state.categoryCounts[q.category]||0)+1;state.answered=false;renderQuestion(q);}
function renderQuestion(q){$('modeLabel').textContent=state.mode==='cases'?'CASOS EXPERT':state.mode==='pharm'?'FARMACOLOGIA EXPERT':state.mode==='errors'?'REVISÃO DE ERROS':state.mode==='quick'?'SPRINT EXPERT':'EXPERT EXAM';$('categoryLabel').textContent=q.category;$('progressText').textContent=`${state.index+1} / ${state.length}`;$('difficultyText').textContent='Expert • 5/5';$('progressBar').style.width=`${(state.index/state.length)*100}%`;$('questionText').textContent=q.q;const caseBox=$('caseBox');if(q.case){caseBox.textContent=q.case;caseBox.classList.remove('hidden')}else caseBox.classList.add('hidden');const options=$('options');options.innerHTML='';q.options.forEach((opt,i)=>{const b=document.createElement('button');b.className='option';b.type='button';b.innerHTML=`<span class="letter">${letters[i]}</span><span>${opt}</span>`;b.addEventListener('click',()=>answer(i,b));options.appendChild(b)});$('feedback').className='feedback hidden';$('feedback').innerHTML='';$('nextBtn').classList.add('hidden');}
function answer(choice,button){if(state.answered)return;state.answered=true;const q=state.current;const correct=choice===q.answer;const buttons=[...document.querySelectorAll('.option')];buttons.forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');});if(!correct)button.classList.add('wrong');const source=window.KSA_SOURCES[q.source]||null;const sourceHtml=source?(source.url?`<a href="${source.url}" target="_blank" rel="noopener">Fonte: ${source.label} ↗</a>`:`<span class="muted">Fonte: ${source.label}</span>`):'';const feedback=$('feedback');feedback.className='feedback '+(correct?'correct':'wrong');feedback.innerHTML=`<h4>${correct?'✓ Correto':'✕ Incorreto — resposta: '+letters[q.answer]}</h4><p>${q.rationale}</p>${sourceHtml}`;state.session.push({id:q.id,category:q.category,correct});const s=loadStats();s.answered=(s.answered||0)+1;if(correct)s.correct=(s.correct||0)+1;let wrong=new Set(s.wrongIds||[]);if(correct)wrong.delete(q.id);else wrong.add(q.id);s.wrongIds=[...wrong];saveStats(s);$('nextBtn').classList.remove('hidden');$('nextBtn').textContent=state.index+1>=state.length?'Ver resultado':'Próxima questão';}
function finish(){if(!state.session.length){showView('home');return;}const total=state.session.length;const correct=state.session.filter(x=>x.correct).length;const pct=Math.round(correct/total*100);$('resultAccuracy').textContent=pct+'%';$('resultDetail').textContent=`${correct} de ${total} corretas`;$('resultTitle').textContent=pct>=85?'Expert Exam — desempenho excelente':pct>=70?'Expert Exam — competitivo':'Expert Exam — revisar raciocínio avançado';const by={};state.session.forEach(x=>{by[x.category]??={n:0,c:0};by[x.category].n++;if(x.correct)by[x.category].c++;});$('resultBreakdown').innerHTML=Object.entries(by).sort((a,b)=>a[0].localeCompare(b[0])).map(([cat,v])=>`<div><span>${cat}</span><strong>${Math.round(v.c/v.n*100)}%</strong></div>`).join('');$('progressBar').style.width='100%';updateHome();showView('result');}
$('nextBtn').addEventListener('click',()=>{state.index++;nextQuestion()});$('quitBtn').addEventListener('click',finish);$('homeBtn').addEventListener('click',()=>{updateHome();showView('home')});$('resultHomeBtn').addEventListener('click',()=>{updateHome();showView('home')});$('restartBtn').addEventListener('click',()=>start(state.lastMode));document.querySelectorAll('.mode-card').forEach(b=>b.addEventListener('click',()=>start(b.dataset.mode)));$('resetStats').addEventListener('click',()=>{if(confirm('Apagar todo o histórico de desempenho e erros deste navegador?')){localStorage.removeItem(STORAGE);updateHome();}});updateHome();
})();