window.KSA_QUESTIONS.push(...[
{id:126,category:'Transfusion & Pharmacology',difficulty:2,q:'Which medication is the specific reversal agent for benzodiazepines?',options:['Naloxone','Flumazenil','Protamine sulfate','Vitamin K','Atropine'],answer:1,rationale:'Flumazenil is a benzodiazepine receptor antagonist used in selected cases of benzodiazepine toxicity.',source:'STANDARD_PHARM'},
{id:127,category:'Transfusion & Pharmacology',difficulty:2,case:'A postoperative patient receiving opioids becomes difficult to arouse with RR 6/min.',q:'Which medication should the nurse anticipate for reversal if clinically indicated?',options:['Naloxone','Phytonadione','Protamine sulfate','Flumazenil','Digoxin immune Fab'],answer:0,rationale:'Naloxone reverses opioid effects and is used for clinically significant opioid-induced respiratory depression.',source:'STANDARD_PHARM'},
{id:128,category:'Transfusion & Pharmacology',difficulty:2,q:'Which medication reverses unfractionated heparin?',options:['Protamine sulfate','Vitamin K','Naloxone','Flumazenil','Glucagon'],answer:0,rationale:'Protamine sulfate neutralizes unfractionated heparin.',source:'ACCP_HEPARIN'},
{id:129,category:'Transfusion & Pharmacology',difficulty:3,case:'A patient on warfarin develops life-threatening bleeding.',q:'Which therapy is commonly part of urgent reversal strategy?',options:['Vitamin K with appropriate factor replacement such as PCC according to protocol','Naloxone only','Protamine alone','Flumazenil only','Regular insulin only'],answer:0,rationale:'Major warfarin-associated bleeding generally requires vitamin K plus rapid replacement of vitamin K-dependent clotting factors, commonly with PCC per protocol.',source:'ACCP_ANTICOAG'},
{id:130,category:'Transfusion & Pharmacology',difficulty:3,q:'Why is an independent double-check often required for selected high-alert medications?',options:['To reduce risk of serious dosing or administration errors','To make medications work faster','To replace patient identification','To avoid documenting administration','To allow verbal orders without verification'],answer:0,rationale:'Independent verification is a safety barrier for medications in which errors can cause severe harm.',source:'STANDARD_NURSING'},
{id:131,category:'Transfusion & Pharmacology',difficulty:2,case:'A patient receiving IV potassium complains of burning at the IV site.',q:'What should the nurse do?',options:['Increase the infusion rate.','Assess the IV site and infusion, verify dilution/rate and follow policy; never give IV potassium by rapid IV push.','Give the remaining potassium as IV push.','Ignore because burning is always expected.','Disconnect the pump and let it run by gravity rapidly.'],answer:1,rationale:'IV potassium requires controlled dilution/rate and careful site monitoring because rapid administration can cause life-threatening complications.',source:'STANDARD_PHARM'},
{id:132,category:'Transfusion & Pharmacology',difficulty:2,q:'Which medication class most commonly increases postoperative bleeding risk and therefore requires careful review around surgery?',options:['Anticoagulants','Topical moisturizers','Saline nasal spray','Fiber supplements','Artificial tears'],answer:0,rationale:'Anticoagulants can increase surgical bleeding risk and require perioperative planning.',source:'ACCP_ANTICOAG'},
{id:133,category:'Transfusion & Pharmacology',difficulty:3,case:'A patient on insulin is NPO for surgery and becomes diaphoretic, shaky and confused.',q:'What should the nurse suspect first?',options:['Hypoglycemia','Hypercalcemia','Pulmonary embolism','Wound dehiscence','DVT'],answer:0,rationale:'Autonomic symptoms and confusion in an insulin-treated fasting patient are classic for hypoglycemia and warrant immediate glucose assessment/treatment per protocol.',source:'STANDARD_PHARM'},
{id:134,category:'Transfusion & Pharmacology',difficulty:2,q:'Which medication should generally be avoided as an IV push because of risk of fatal dysrhythmias?',options:['Potassium chloride','Normal saline','Ondansetron at an approved dose','Acetaminophen orally','Subcutaneous heparin prophylaxis'],answer:0,rationale:'Concentrated potassium must never be administered by rapid IV push; it requires controlled dilution and infusion.',source:'STANDARD_PHARM'},
{id:135,category:'Transfusion & Pharmacology',difficulty:3,case:'Ten minutes after a blood transfusion starts, the patient develops fever, chills, dyspnea and lumbar pain.',q:'What is the first action?',options:['Stop the transfusion immediately and assess the patient.','Increase the rate to finish the unit.','Discard all tubing before notifying anyone.','Give a meal.','Wait 30 minutes.'],answer:0,rationale:'A suspected acute transfusion reaction requires immediate cessation of the transfusion and patient assessment.',source:'NHS_TRANSFUSION'},
{id:136,category:'Transfusion & Pharmacology',difficulty:3,q:'After stopping a suspected transfusion reaction, what is an appropriate next step?',options:['Maintain IV access with compatible fluid/new tubing as required and notify the appropriate clinical/blood bank teams.','Restart the same unit immediately.','Remove all IV access.','Send the patient home.','Destroy the blood bag before investigation.'],answer:0,rationale:'Maintaining venous access, reassessing the patient and notifying the relevant teams are standard early steps after stopping a reaction.',source:'NHS_TRANSFUSION'},
{id:137,category:'Transfusion & Pharmacology',difficulty:2,q:'Which finding after opioid administration requires the most urgent reassessment?',options:['Pain decreased from 8/10 to 5/10','RR 8/min with increasing sedation','Mild nausea with normal respirations','Dry mouth','Patient asks for water'],answer:1,rationale:'Bradypnea plus increasing sedation is a red flag for opioid-induced respiratory depression.',source:'STANDARD_PHARM'},
{id:138,category:'Transfusion & Pharmacology',difficulty:3,case:'A patient taking an ACE inhibitor has potassium 6.2 mmol/L and new peaked T waves.',q:'What is the nurse\'s priority?',options:['Recognize potentially dangerous hyperkalemia and notify the clinical team urgently while monitoring cardiac status.','Give potassium supplementation.','Encourage a potassium-rich meal.','Ignore because potassium affects only muscles.','Discontinue cardiac monitoring.'],answer:0,rationale:'Severe hyperkalemia with ECG changes can cause life-threatening dysrhythmias and requires urgent treatment.',source:'STANDARD_CLINICAL'},
{id:139,category:'Transfusion & Pharmacology',difficulty:3,q:'Which combination is most consistent with digoxin toxicity?',options:['Nausea, visual changes and bradyarrhythmia','Polyuria and hypertension only','Unilateral calf swelling','Stridor after thyroid surgery','Purulent wound drainage'],answer:0,rationale:'Digoxin toxicity can produce gastrointestinal, visual and cardiac conduction abnormalities.',source:'STANDARD_PHARM'},
{id:140,category:'Transfusion & Pharmacology',difficulty:2,q:'Before administering an antibiotic, which safety check is especially important?',options:['Verify allergy history and the medication order','Ask the patient\'s roommate if they have allergies','Skip identification if the drug is common','Document administration before giving it','Use the room number as the only identifier'],answer:0,rationale:'Medication safety requires confirming the correct patient/order and checking relevant allergy history.',source:'STANDARD_NURSING'}
]);
