window.KSA_QUESTIONS.push(...[
{id:141,category:'Fluids / Electrolytes / Calculations',difficulty:2,q:'An IV order is 1,500 mL over 12 hours. What pump rate should be programmed?',options:['100 mL/h','110 mL/h','125 mL/h','150 mL/h','180 mL/h'],answer:2,rationale:'1500 ÷ 12 = 125 mL/hour.',source:'CALC'},
{id:142,category:'Fluids / Electrolytes / Calculations',difficulty:2,q:'A medication order is 1 g. The vial contains 500 mg in 5 mL. How many mL should be administered?',options:['2.5 mL','5 mL','7.5 mL','10 mL','15 mL'],answer:3,rationale:'1 g = 1000 mg. (1000 ÷ 500) × 5 mL = 10 mL.',source:'CALC'},
{id:143,category:'Fluids / Electrolytes / Calculations',difficulty:3,q:'A medication is ordered at 0.1 mg/kg for an 80-kg patient. What total dose is required?',options:['0.8 mg','4 mg','8 mg','40 mg','80 mg'],answer:2,rationale:'0.1 mg × 80 kg = 8 mg.',source:'CALC'},
{id:144,category:'Fluids / Electrolytes / Calculations',difficulty:3,q:'An infusion contains 400 mg in 250 mL. The order is 20 mg/hour. What pump rate is required?',options:['6.25 mL/h','10 mL/h','12.5 mL/h','20 mL/h','25 mL/h'],answer:2,rationale:'Concentration = 400 mg/250 mL = 1.6 mg/mL. 20 mg ÷ 1.6 = 12.5 mL/hour.',source:'CALC'},
{id:145,category:'Fluids / Electrolytes / Calculations',difficulty:3,q:'An IV of 1,000 mL must infuse over 10 hours using tubing with a drop factor of 15 gtt/mL. Approximately how many drops per minute are needed?',options:['15 gtt/min','20 gtt/min','25 gtt/min','30 gtt/min','40 gtt/min'],answer:2,rationale:'(1000 mL × 15 gtt/mL) ÷ 600 min = 25 gtt/min.',source:'CALC'},
{id:146,category:'Fluids / Electrolytes / Calculations',difficulty:3,q:'A vasopressor is ordered at 0.05 mcg/kg/min for a 70-kg patient. What dose is required per minute?',options:['0.35 mcg/min','1.4 mcg/min','3.5 mcg/min','7 mcg/min','35 mcg/min'],answer:2,rationale:'0.05 × 70 = 3.5 mcg/min.',source:'CALC'},
{id:147,category:'Fluids / Electrolytes / Calculations',difficulty:2,case:'A patient 6 hours after surgery has dry mucous membranes, tachycardia, orthostatic dizziness and concentrated urine.',q:'Which problem is most consistent with these findings?',options:['Possible volume depletion','Fluid overload','Hypervolemia with pulmonary edema','Isolated DVT','Airway obstruction'],answer:0,rationale:'Tachycardia, orthostatic symptoms and concentrated urine can occur with intravascular volume depletion.',source:'STANDARD_CLINICAL'},
{id:148,category:'Fluids / Electrolytes / Calculations',difficulty:2,case:'A patient receiving large volumes of IV fluid develops dyspnea, new crackles and increasing peripheral edema.',q:'What should the nurse suspect?',options:['Fluid overload','Hypovolemia only','DVT in every case','Hypoglycemia','Wound dehiscence'],answer:0,rationale:'Dyspnea, crackles and edema during fluid administration can indicate volume overload and require reassessment.',source:'STANDARD_CLINICAL'},
{id:149,category:'Fluids / Electrolytes / Calculations',difficulty:3,q:'Which ECG-related concern is associated with significant hyperkalemia?',options:['Peaked T waves and potentially dangerous conduction abnormalities','Only sinus tachycardia with no other changes','No cardiac effects','Isolated prolonged QT from every case','Only atrial flutter'],answer:0,rationale:'Hyperkalemia can cause peaked T waves and progressive conduction disturbances that may become life-threatening.',source:'STANDARD_CLINICAL'},
{id:150,category:'Fluids / Electrolytes / Calculations',difficulty:2,q:'Which symptom cluster is most consistent with hypokalemia?',options:['Muscle weakness, cramps and possible dysrhythmias','Severe unilateral calf swelling only','Stridor and neck swelling','Purulent drainage only','Sudden pleuritic chest pain'],answer:0,rationale:'Low potassium may cause neuromuscular weakness and cardiac rhythm abnormalities.',source:'STANDARD_CLINICAL'},
{id:151,category:'Fluids / Electrolytes / Calculations',difficulty:3,case:'A patient has sodium 118 mmol/L and develops confusion and a seizure.',q:'What is the priority?',options:['Treat as symptomatic severe hyponatremia and obtain urgent medical intervention.','Encourage unrestricted free water.','Ignore because sodium affects only thirst.','Ambulate the patient alone.','Give potassium by IV push.'],answer:0,rationale:'Severe symptomatic hyponatremia can cause cerebral edema and seizures and requires urgent treatment.',source:'STANDARD_CLINICAL'},
{id:152,category:'Fluids / Electrolytes / Calculations',difficulty:3,case:'A postoperative patient has magnesium 1.0 mg/dL and frequent ventricular ectopy.',q:'What is the key concern?',options:['Hypomagnesemia may contribute to cardiac irritability and requires prompt correction per order.','Magnesium has no cardiac relevance.','The patient needs a potassium-rich meal only.','The rhythm can be ignored.','The magnesium result proves sepsis.'],answer:0,rationale:'Significant hypomagnesemia can predispose to dysrhythmias and often requires replacement.',source:'STANDARD_CLINICAL'},
{id:153,category:'Fluids / Electrolytes / Calculations',difficulty:2,q:'For a 70-kg adult, which hourly urine output would be especially concerning if persistent and accompanied by hypotension?',options:['10 mL/h','40 mL/h','50 mL/h','70 mL/h','100 mL/h'],answer:0,rationale:'Marked oliguria, particularly with hypotension, suggests reduced renal perfusion or another acute problem.',source:'STANDARD_CLINICAL'},
{id:154,category:'Fluids / Electrolytes / Calculations',difficulty:3,q:'A patient received 2,400 mL intake and had 1,650 mL total output over 24 hours. What is the net fluid balance?',options:['−750 mL','−250 mL','+250 mL','+750 mL','+1,650 mL'],answer:3,rationale:'2400 − 1650 = +750 mL.',source:'CALC'},
{id:155,category:'Fluids / Electrolytes / Calculations',difficulty:2,q:'A 250-mL antibiotic infusion must run over 90 minutes. What pump rate is closest?',options:['100 mL/h','125 mL/h','150 mL/h','167 mL/h','250 mL/h'],answer:3,rationale:'90 minutes = 1.5 hours. 250 ÷ 1.5 ≈ 166.7 mL/hour.',source:'CALC'}
]);
