window.KSA_QUESTIONS.push(...[
{id:156,category:'Prioritization & Communication',difficulty:2,case:'At shift change you receive five patients.',q:'Which patient should you assess first?',options:['Stable patient asking for a blanket','Postoperative patient with new stridor and neck swelling','Patient waiting for routine discharge papers','Stable patient requesting a snack','Patient with chronic pain 4/10 and normal vital signs'],answer:1,rationale:'New stridor indicates an immediate airway threat and takes priority.',source:'STANDARD_NURSING'},
{id:157,category:'Prioritization & Communication',difficulty:3,case:'Two patients call at the same time. Patient A has pain 8/10 but is alert, BP 128/74, RR 16. Patient B is newly confused, BP 82/50 and HR 126.',q:'Who should be seen first?',options:['Patient A because pain is subjective and severe','Patient B because acute hemodynamic/mental-status deterioration is more urgent','Whichever room is closer','Neither until medication rounds are finished','Both are equally stable'],answer:1,rationale:'Acute shock-like deterioration takes priority over severe but hemodynamically stable pain.',source:'STANDARD_NURSING'},
{id:158,category:'Prioritization & Communication',difficulty:3,q:'Which task is most appropriate for an RN to delegate to trained unlicensed assistive personnel according to local policy?',options:['Initial assessment of a newly unstable patient','Interpreting a new arrhythmia','Assisting a stable patient with hygiene and reporting observations','Teaching a new anticoagulant regimen','Deciding whether to activate rapid response'],answer:2,rationale:'Routine care for stable patients may be delegated, while assessment, teaching and clinical judgment remain RN responsibilities.',source:'STANDARD_NURSING'},
{id:159,category:'Prioritization & Communication',difficulty:2,q:'In SBAR, which information belongs in “Assessment”?',options:['Your clinical findings and what you think is happening','Only the patient\'s insurance number','A list of every admission in the hospital','The discharge address only','The cafeteria menu'],answer:0,rationale:'Assessment summarizes relevant clinical findings and the nurse\'s interpretation of the current problem.',source:'STANDARD_NURSING'},
{id:160,category:'Prioritization & Communication',difficulty:3,case:'A surgeon does not immediately respond to your concern about a deteriorating postoperative patient.',q:'What is the best nursing action?',options:['Do nothing because the surgeon was informed once.','Continue to advocate for the patient and escalate through the appropriate chain/rapid response pathway if the safety concern persists.','Wait until the next shift.','Change medical orders independently.','Ask the family to make treatment decisions.'],answer:1,rationale:'Persistent safety concerns require continued escalation through established channels.',source:'AHRQ_RRT'},
{id:161,category:'Prioritization & Communication',difficulty:2,q:'Which documentation entry is best?',options:['Patient looks terrible.','09:20 — BP 84/48, HR 124, skin cool/clammy; surgical drain 180 mL bright-red output in 20 min; rapid response activated and surgeon notified.','Doctor aware.','Bleeding a lot.','Probably shock.'],answer:1,rationale:'Documentation should be objective, specific, time-stamped and describe assessment, actions and escalation.',source:'KFSHRC_STAFFNURSE'},
{id:162,category:'Prioritization & Communication',difficulty:2,case:'A competent patient refuses a recommended procedure after receiving explanation.',q:'What should the nurse do?',options:['Force the procedure.','Respect the decision, explore concerns, ensure the team is informed and document the refusal/education.','Ask security to restrain the patient.','Chart that the procedure was completed.','Hide the refusal from the physician.'],answer:1,rationale:'Patient autonomy requires informed participation, appropriate communication and accurate documentation.',source:'KFSHRC_VALUES'},
{id:163,category:'Prioritization & Communication',difficulty:3,q:'Which patient can generally be seen last?',options:['New postoperative stridor','Sudden SpO₂ 82%','BP 78/44 with confusion','Stable patient awaiting routine discharge instructions','New uncontrolled active bleeding'],answer:3,rationale:'Stable administrative/discharge needs come after acute airway, breathing and circulation threats.',source:'STANDARD_NURSING'},
{id:164,category:'Prioritization & Communication',difficulty:2,q:'Which response best demonstrates closed-loop communication during an emergency?',options:['Silently assume another nurse heard the order.','Repeat back the instruction, confirm it and report completion.','Leave the room without acknowledging the request.','Document the instruction hours later only.','Ask a family member to relay the order.'],answer:1,rationale:'Closed-loop communication confirms that a message was heard, understood and completed.',source:'STANDARD_NURSING'},
{id:165,category:'Prioritization & Communication',difficulty:3,case:'A patient becomes acutely dyspneic while you are preparing routine medications for another stable patient.',q:'What should you do?',options:['Finish all routine medications first.','Address the acutely dyspneic patient immediately and safely defer/reassign routine tasks.','Ask the unstable patient to wait.','Document before assessing.','Give the stable patient extra medication to save time.'],answer:1,rationale:'Acute breathing compromise takes precedence over nonurgent routine tasks.',source:'STANDARD_NURSING'},
{id:166,category:'Prioritization & Communication',difficulty:2,q:'Which statement best describes safe delegation?',options:['The RN transfers all accountability to the delegatee.','The RN considers patient stability, task complexity, staff competence and local policy, then follows up appropriately.','Any task can be delegated if the unit is busy.','Initial assessment is ideal for delegation.','Patient teaching is always delegated.'],answer:1,rationale:'Delegation requires matching the task and patient to the competence of the delegatee while maintaining RN oversight.',source:'STANDARD_NURSING'},
{id:167,category:'Prioritization & Communication',difficulty:3,case:'A UAP reports that a stable postoperative patient now has BP 86/50 and appears confused.',q:'What should the RN do next?',options:['Ask the UAP to decide whether this is shock.','Personally assess the patient immediately and escalate based on findings.','Wait until lunch.','Tell the UAP to repeat the pressure in four hours.','Document without seeing the patient.'],answer:1,rationale:'A new abnormal finding in a potentially unstable patient requires RN assessment and clinical judgment.',source:'STANDARD_NURSING'},
{id:168,category:'Prioritization & Communication',difficulty:2,q:'Which statement is the best “Recommendation” in an SBAR call?',options:['I think he is sick.','I need you to review the patient urgently now; he is hypotensive with increasing bright-red drain output and may require further resuscitation or return to theatre.','He had surgery yesterday.','His family is visiting.','His room is 412.'],answer:1,rationale:'A strong recommendation clearly states the requested action and urgency.',source:'STANDARD_NURSING'},
{id:169,category:'Prioritization & Communication',difficulty:3,q:'What is the safest response when you are unsure whether an unfamiliar order is appropriate?',options:['Carry it out without question.','Pause, verify the order and seek clarification through the appropriate clinical/pharmacy chain before administration.','Ask another patient what to do.','Ignore the order permanently.','Change the dose yourself.'],answer:1,rationale:'Unclear or potentially unsafe orders should be clarified before implementation.',source:'STANDARD_NURSING'},
{id:170,category:'Prioritization & Communication',difficulty:2,case:'A family member is angry about a delay and begins speaking loudly at the nurses\' station.',q:'Which response is best?',options:['Argue publicly.','Remain calm, acknowledge the concern, move the conversation to a private area if safe and address the issue while maintaining boundaries.','Ignore the person completely.','Discuss another patient\'s condition to distract them.','Promise an outcome you cannot guarantee.'],answer:1,rationale:'Professional de-escalation uses calm communication, privacy, boundaries and realistic information.',source:'KFSHRC_VALUES'}
]);
