window.KSA_QUESTIONS.push(...[
{id:96,category:'Respiratory / DVT / PE',difficulty:2,case:'A postoperative patient has shallow respirations, diminished breath sounds at the bases and SpO₂ 90% while lying supine.',q:'Which intervention is most appropriate if not contraindicated?',options:['Keep the patient flat and immobile.','Reposition upright, encourage deep breathing/incentive spirometry and mobilize as tolerated.','Give a sedative.','Restrict all coughing.','Turn off oxygen regardless of saturation.'],answer:1,rationale:'Positioning, lung-expansion exercises and early mobilization are key measures for common postoperative atelectatic changes.',source:'NCBI_PERIOP'},
{id:97,category:'Respiratory / DVT / PE',difficulty:3,case:'A patient suddenly develops dyspnea, pleuritic chest pain, HR 128 and SpO₂ 86% on postoperative day 3.',q:'What is the nurse\'s priority action?',options:['Massage the calf to improve venous return.','Assess and support ABCs, provide oxygen as indicated and activate urgent medical evaluation for possible PE.','Wait for the next scheduled observations.','Encourage the patient to walk.','Give oral fluids only.'],answer:1,rationale:'Possible pulmonary embolism with hypoxemia requires immediate stabilization and urgent escalation.',source:'CDC_VTE'},
{id:98,category:'Respiratory / DVT / PE',difficulty:2,q:'Which patient is at highest risk for postoperative VTE?',options:['Ambulatory young adult after minor skin surgery','Older patient after major pelvic surgery with prolonged immobility and previous DVT','Healthy adult walking independently after day surgery','Patient with seasonal rhinitis','Patient with a minor superficial wound'],answer:1,rationale:'Major surgery, immobility and prior VTE substantially increase thromboembolic risk.',source:'CDC_VTE'},
{id:99,category:'Respiratory / DVT / PE',difficulty:2,q:'Which nursing action is appropriate when DVT is suspected?',options:['Massage the affected calf vigorously.','Limit unnecessary manipulation of the limb and notify the clinical team promptly for evaluation.','Apply a tourniquet above the knee.','Encourage intense exercise.','Ignore unilateral swelling if the patient has no fever.'],answer:1,rationale:'Suspected DVT requires prompt clinical evaluation; vigorous massage is inappropriate.',source:'CDC_VTE'},
{id:100,category:'Respiratory / DVT / PE',difficulty:3,case:'A postoperative patient receiving opioids has RR 8/min and SpO₂ 97% on 5 L/min oxygen.',q:'Which interpretation is best?',options:['The patient is stable because SpO₂ is normal.','The low respiratory rate may indicate dangerous hypoventilation despite a preserved saturation on supplemental oxygen.','Supplemental oxygen rules out opioid toxicity.','The respiratory rate can be ignored.','The patient should receive another opioid immediately.'],answer:1,rationale:'Supplemental oxygen can maintain SpO₂ despite inadequate ventilation. Bradypnea still requires urgent assessment.',source:'STANDARD_CLINICAL'},
{id:101,category:'Respiratory / DVT / PE',difficulty:3,case:'A patient after neck surgery develops sudden stridor, hoarseness and increasing neck swelling.',q:'What complication is the greatest immediate concern?',options:['Constipation','Airway obstruction from postoperative swelling/hematoma','DVT in the leg','Urinary retention','Mild dehydration'],answer:1,rationale:'Stridor and neck swelling after neck surgery can rapidly threaten the airway and demand emergency response.',source:'NCBI_PERIOP'},
{id:102,category:'Respiratory / DVT / PE',difficulty:2,q:'Which finding is more suggestive of atelectasis than pulmonary embolism?',options:['Gradual shallow breathing with reduced basilar breath sounds after abdominal surgery','Sudden pleuritic chest pain with acute hypoxemia','Sudden syncope and hypotension','Unilateral calf swelling followed by acute dyspnea','Abrupt unexplained tachycardia with chest pain'],answer:0,rationale:'Atelectasis commonly presents with reduced ventilation at the lung bases and may develop gradually after surgery, whereas PE is often more abrupt.',source:'NCBI_PERIOP'},
{id:103,category:'Respiratory / DVT / PE',difficulty:3,case:'A patient with a chest tube suddenly becomes dyspneic. The drainage tubing is disconnected from the collection system.',q:'What should the nurse do?',options:['Leave the system disconnected.','Immediately restore the system according to emergency chest-tube protocol, assess ABCs and escalate if the patient remains unstable.','Remove the chest tube.','Clamp the tube indefinitely.','Ask the patient to hold the tube while walking.'],answer:1,rationale:'Loss of chest-tube system integrity can compromise pleural drainage and requires immediate system correction plus respiratory assessment.',source:'STANDARD_CLINICAL'},
{id:104,category:'Respiratory / DVT / PE',difficulty:2,q:'Which intervention most directly promotes venous return and helps reduce postoperative DVT risk in an appropriate patient?',options:['Prolonged bed rest','Early ambulation and prescribed compression/prophylaxis','Dehydration','Keeping the knees flexed continuously','Massaging any painful calf'],answer:1,rationale:'Early mobility and appropriate mechanical or pharmacologic prophylaxis are standard VTE-prevention measures.',source:'CDC_VTE'},
{id:105,category:'Respiratory / DVT / PE',difficulty:3,case:'A postoperative patient has sudden dyspnea and hypotension. While awaiting the emergency team, SpO₂ continues to fall.',q:'What should the nurse prioritize?',options:['Completing the discharge summary','Airway/breathing support, oxygenation and continuous reassessment of circulation','Obtaining a meal tray','Removing all monitoring equipment','Walking the patient to radiology'],answer:1,rationale:'In an unstable patient, immediate ABC support comes before diagnostic logistics or routine tasks.',source:'AHRQ_RRT'},
{id:106,category:'Respiratory / DVT / PE',difficulty:2,q:'Which symptom combination should raise concern for pulmonary embolism after surgery?',options:['Sudden dyspnea, tachycardia and pleuritic chest pain','Mild incisional itching and stable vital signs','Gradual improvement in pain and mobility','Normal oxygen saturation with no symptoms','Constipation and dry skin only'],answer:0,rationale:'Sudden dyspnea, tachycardia and pleuritic chest pain are classic warning features of PE.',source:'CDC_VTE'},
{id:107,category:'Respiratory / DVT / PE',difficulty:3,case:'A patient on prophylactic anticoagulation develops unilateral calf swelling and tenderness.',q:'Which statement is most accurate?',options:['Prophylaxis completely excludes DVT.','DVT can still occur despite prophylaxis, so the new symptoms require prompt evaluation.','The nurse should double the anticoagulant dose independently.','The calf should be deeply massaged.','The symptoms can be ignored until discharge.'],answer:1,rationale:'Prophylaxis reduces but does not eliminate VTE risk; new unilateral symptoms still require assessment.',source:'CDC_VTE'},
{id:108,category:'Respiratory / DVT / PE',difficulty:2,case:'A patient with obstructive sleep apnea is receiving opioids after surgery.',q:'Which nursing concern is especially important?',options:['Reduced risk of respiratory depression','Enhanced monitoring for sedation and respiratory compromise','Avoiding all oxygen assessments','Giving sedatives with every opioid dose','Keeping the patient unmonitored overnight'],answer:1,rationale:'Sleep apnea and opioid use can increase the risk of postoperative respiratory depression and warrant close monitoring.',source:'STANDARD_CLINICAL'},
{id:109,category:'Respiratory / DVT / PE',difficulty:3,case:'A patient has RR 30, SpO₂ 88%, new anxiety and absent breath sounds on one side after a central line procedure.',q:'What is the best interpretation?',options:['Possible acute pneumothorax requiring urgent evaluation','Simple hunger','Constipation','Routine postoperative fatigue','Expected effect of IV fluids'],answer:0,rationale:'Acute dyspnea with unilateral absent breath sounds after an invasive thoracic procedure raises concern for pneumothorax.',source:'STANDARD_CLINICAL'},
{id:110,category:'Respiratory / DVT / PE',difficulty:3,q:'Why is new unexplained tachycardia important in a postoperative patient?',options:['It can be an early sign of complications such as bleeding, pain, infection, hypoxia or PE and should be interpreted in context.','It is always benign after surgery.','It proves the patient is dehydrated.','It should never influence nursing assessment.','It only matters if the heart rate exceeds 180.'],answer:0,rationale:'Tachycardia is nonspecific but can be an early marker of several serious postoperative complications.',source:'AHRQ_RRT'}
]);
