window.KSA_QUESTIONS.push(...[
{id:171,category:'Wounds & Drains',difficulty:2,case:'A JP drain that had produced 40 mL every 4 hours suddenly has no output, while the patient develops increasing localized swelling and pain.',q:'What should the nurse do?',options:['Assume the drain is no longer needed.','Assess the drain for kinks/obstruction, inspect the site and patient, and notify the surgical team if concern persists.','Remove the drain immediately without an order.','Flush it forcefully regardless of policy.','Ignore because zero output is always good.'],answer:1,rationale:'A sudden stop in output with swelling/pain may indicate obstruction or fluid accumulation and requires assessment.',source:'NCBI_PERIOP'},
{id:172,category:'Wounds & Drains',difficulty:2,q:'Which change in wound drainage is most concerning?',options:['Small decreasing amount of serosanguineous drainage','New foul-smelling purulent drainage with increasing erythema','Dry intact dressing','Gradually decreasing tenderness','Well-approximated edges'],answer:1,rationale:'Purulent malodorous drainage with increasing inflammation is concerning for infection.',source:'NCBI_WOUND'},
{id:173,category:'Wounds & Drains',difficulty:3,case:'A patient coughs and the abdominal incision partially separates, but no organs are visible.',q:'What should the nurse do?',options:['Apply pressure and force the edges together.','Reduce strain, cover with a sterile dressing as appropriate, assess the patient and notify the surgical team promptly.','Ask the patient to walk.','Leave the wound open to air and discharge.','Give food before assessment.'],answer:1,rationale:'Wound dehiscence requires protection of the wound, reduction of tension and prompt surgical evaluation.',source:'NCBI_WOUND'},
{id:174,category:'Wounds & Drains',difficulty:3,case:'A patient with abdominal evisceration asks the nurse to push the bowel back inside.',q:'What is the correct response?',options:['Gently push it back.','Do not reinsert exposed organs; protect them with sterile saline-moistened/nonadherent material and obtain urgent surgical help.','Cover with dry paper towels.','Encourage standing.','Apply direct pressure to the bowel.'],answer:1,rationale:'Exposed viscera should not be pushed back; they must be protected while urgent surgical management is arranged.',source:'NCBI_WOUND'},
{id:175,category:'Wounds & Drains',difficulty:2,q:'Which nursing action is appropriate for a closed-suction drain?',options:['Measure output and document amount, color and character.','Open the system routinely to air.','Discard drainage without measuring it.','Clamp continuously.','Remove it when the patient requests.'],answer:0,rationale:'Drain trends help identify bleeding, infection or obstruction and should be accurately documented.',source:'NCBI_PERIOP'},
{id:176,category:'Wounds & Drains',difficulty:3,case:'A patient with an NG tube after bowel surgery develops nausea and abdominal distention. The tube appears to have stopped draining.',q:'What is the best nursing response?',options:['Remove the tube immediately.','Check prescribed suction/setup, tubing position and patency according to policy, assess the patient and notify the team if unresolved.','Give a large meal.','Clamp the tube indefinitely.','Ignore the symptoms.'],answer:1,rationale:'Loss of NG decompression with recurrent distention/nausea may reflect obstruction or malfunction and requires assessment.',source:'STANDARD_CLINICAL'},
{id:177,category:'Wounds & Drains',difficulty:2,q:'Which practice is safest for a urinary catheter drainage system?',options:['Maintain a closed system and unobstructed urine flow.','Disconnect tubing each shift for cleaning.','Keep the bag above bladder level.','Allow tubing to kink under the patient.','Use the sampling port without aseptic technique.'],answer:0,rationale:'Maintaining a closed, unobstructed system and proper bag positioning helps reduce CAUTI risk.',source:'CDC_CAUTI'},
{id:178,category:'Transfusion & Pharmacology',difficulty:3,case:'A patient develops dyspnea and crackles during transfusion but no fever or back pain; BP rises and jugular veins appear distended.',q:'Which complication should be considered?',options:['Transfusion-associated circulatory overload','Isolated hypoglycemia','DVT only','Wound dehiscence','Opioid withdrawal'],answer:0,rationale:'Dyspnea, pulmonary congestion and signs of volume overload during transfusion can suggest circulatory overload.',source:'NHS_TRANSFUSION'},
{id:179,category:'Transfusion & Pharmacology',difficulty:2,q:'Why are baseline vital signs obtained before a blood transfusion?',options:['To provide a comparison if symptoms or physiologic changes occur during transfusion','Only for billing','To determine the patient\'s diet','To replace blood-type verification','Because no monitoring is needed after transfusion begins'],answer:0,rationale:'Baseline observations help identify new changes during transfusion and support early recognition of reactions.',source:'NHS_TRANSFUSION'},
{id:180,category:'Preoperative Care',difficulty:2,q:'Which preoperative discrepancy requires resolution before surgery proceeds?',options:['Patient identity band matches the chart','Consent lists the left knee but the schedule lists the right knee','Patient has changed into a gown','Baseline vital signs are documented','Jewelry has been removed'],answer:1,rationale:'Any mismatch involving patient, procedure or site is a major safety issue and must be resolved before surgery.',source:'WHO_SURGICAL'},
{id:181,category:'Preoperative Care',difficulty:2,q:'Which question is particularly important in preoperative medication reconciliation?',options:['Do you take anticoagulants, antiplatelet drugs, insulin or other medications that may affect perioperative care?','What is your favorite color?','What television shows do you watch?','Do you prefer morning or evening meals?','How many pillows are at home?'],answer:0,rationale:'Medication reconciliation identifies drugs that may alter bleeding, glycemic control, hemodynamics or anesthesia risk.',source:'STANDARD_NURSING'},
{id:182,category:'Preoperative Care',difficulty:3,case:'A patient says, “I signed the consent, but I still do not understand what surgery I am having.”',q:'What should the nurse do?',options:['Tell the patient the signature means questions are no longer allowed.','Pause progression and notify the appropriate clinician so the patient can receive adequate explanation before proceeding.','Explain all surgical risks independently beyond scope.','Sedate the patient before further discussion.','Ignore because the form is signed.'],answer:1,rationale:'Valid informed consent requires understanding and an opportunity for questions; unresolved uncertainty should be addressed before proceeding.',source:'WHO_SURGICAL'},
{id:183,category:'Preoperative Care',difficulty:2,q:'The WHO Surgical Safety Checklist is organized around which major perioperative checkpoints?',options:['Before anesthesia induction, before skin incision and before leaving the operating room','Admission, discharge and billing','Breakfast, lunch and dinner','Pre-op clinic only','After discharge only'],answer:0,rationale:'The checklist uses key pauses before induction, before incision and before the patient/team leaves the operating room.',source:'WHO_SURGICAL'},
{id:184,category:'Preoperative Care',difficulty:3,case:'A patient scheduled for surgery reports a severe latex allergy that is not documented in the chart.',q:'What is the priority nursing action?',options:['Ignore because the surgery is already booked.','Document and communicate the allergy immediately so the perioperative team can implement appropriate precautions.','Ask the patient to remove the allergy bracelet.','Give latex gloves to test the reaction.','Wait until after surgery.'],answer:1,rationale:'Unrecognized severe allergy can cause life-threatening perioperative exposure and must be communicated before surgery.',source:'WHO_SURGICAL'},
{id:185,category:'Preoperative Care',difficulty:2,q:'Why is a surgical time-out performed immediately before incision?',options:['To confirm critical safety information with the team before an irreversible step','To decide the patient\'s discharge diet','To replace informed consent','To calculate payroll','To allow family visiting'],answer:0,rationale:'The time-out creates a final shared verification of patient, procedure, site and anticipated critical events.',source:'WHO_SURGICAL'}
]);
