window.KSA_QUESTIONS.push(...[
{id:111,category:'Sepsis',difficulty:2,case:'A postoperative patient has T 38.9°C, HR 122, RR 26, BP 94/58 and new confusion.',q:'What is the best nursing response?',options:['Assume this is routine postoperative fever.','Recognize possible sepsis/clinical deterioration, assess perfusion and escalate promptly.','Give only acetaminophen and reassess tomorrow.','Remove monitoring equipment.','Delay action until blood cultures are positive.'],answer:1,rationale:'Possible infection plus hemodynamic and neurologic changes warrants urgent sepsis assessment and escalation.',source:'SCCM_SEPSIS'},
{id:112,category:'Sepsis',difficulty:3,q:'Which statement about sepsis screening is most accurate?',options:['qSOFA alone should be the only screening method in hospitalized patients.','Current guidance favors tools such as NEWS/NEWS2, MEWS or SIRS over qSOFA as a single screening tool in hospitalized acutely ill adults.','A single biomarker rules sepsis in or out.','Temperature alone is sufficient.','Screening tools replace clinical judgment.'],answer:1,rationale:'Current Surviving Sepsis guidance recommends NEWS/NEWS2, MEWS or SIRS over qSOFA alone for hospital screening and emphasizes clinical diagnosis.',source:'SCCM_SEPSIS'},
{id:113,category:'Sepsis',difficulty:3,case:'A patient with suspected septic shock is hypotensive after initial crystalloid resuscitation.',q:'Which vasopressor is recommended first-line?',options:['Norepinephrine','Digoxin','Furosemide','Adenosine','Atropine'],answer:0,rationale:'Norepinephrine is recommended as the first-line vasopressor in septic shock.',source:'SCCM_SEPSIS'},
{id:114,category:'Sepsis',difficulty:2,q:'Why should blood cultures ideally be obtained before antibiotics in suspected sepsis when this does not cause harmful delay?',options:['To help identify the causative organism and guide antimicrobial therapy','To replace all other laboratory tests','Because antibiotics cannot work without cultures','To avoid measuring lactate','Because cultures immediately cure infection'],answer:0,rationale:'Cultures can identify pathogens and support targeted therapy, but treatment should not be dangerously delayed to obtain them.',source:'SCCM_SEPSIS'},
{id:115,category:'Sepsis',difficulty:3,case:'A septic patient received initial fluids. BP improves, capillary refill shortens and urine output begins to rise.',q:'What is the best interpretation?',options:['These findings may indicate improving perfusion, but ongoing reassessment is required.','Sepsis is cured and monitoring can stop.','All antibiotics can be stopped immediately.','Further assessment is unnecessary.','Urine output is unrelated to perfusion.'],answer:0,rationale:'Improvement in perfusion markers is encouraging but resuscitation and treatment require repeated reassessment.',source:'SCCM_SEPSIS'},
{id:116,category:'Sepsis',difficulty:2,q:'Which finding can occur in sepsis even if the patient is not febrile?',options:['Hypothermia with tachycardia and altered mental status','A normal temperature always excludes sepsis.','Only isolated itching','Stable vital signs with no symptoms','Normal mentation excludes infection.'],answer:0,rationale:'Sepsis can occur without fever; hypothermia and other systemic changes can be concerning.',source:'SCCM_SEPSIS'},
{id:117,category:'Infection & Patient Safety',difficulty:1,q:'When should Standard Precautions be used?',options:['Only for patients with known multidrug-resistant organisms','For all patients, regardless of known infection status','Only in the operating room','Only when blood is visible','Only during invasive procedures'],answer:1,rationale:'Standard Precautions apply to all patient care and are based on anticipated exposure risk.',source:'CDC_STANDARD'},
{id:118,category:'Infection & Patient Safety',difficulty:2,q:'Which action best reduces risk of CAUTI?',options:['Keep urinary catheters in place for convenience.','Use catheters only for appropriate indications and remove them as soon as no longer needed.','Disconnect the closed system daily.','Place the drainage bag above bladder level.','Irrigate routinely without indication.'],answer:1,rationale:'Minimizing unnecessary catheter use and duration is a core CAUTI-prevention principle.',source:'CDC_CAUTI'},
{id:119,category:'Infection & Patient Safety',difficulty:2,q:'Where should an indwelling urinary drainage bag be positioned?',options:['Above the bladder','Below the level of the bladder without resting on the floor','At the same level as the patient\'s chest','On the patient\'s abdomen','Disconnected whenever the patient walks'],answer:1,rationale:'Keeping the bag below bladder level helps prevent reflux while maintaining a closed system.',source:'CDC_CAUTI'},
{id:120,category:'Infection & Patient Safety',difficulty:3,case:'A postoperative patient with a urinary catheter develops new fever and suprapubic discomfort. The catheter is no longer clinically necessary.',q:'What is an appropriate nursing action?',options:['Keep the catheter indefinitely.','Notify the team, assess for infection and support prompt removal if no longer indicated according to protocol.','Raise the drainage bag above the bladder.','Disconnect the tubing to obtain air circulation.','Give antibiotics independently.'],answer:1,rationale:'Unnecessary catheter duration increases CAUTI risk; symptoms require assessment and the catheter should be removed when no longer indicated.',source:'CDC_CAUTI'},
{id:121,category:'Infection & Patient Safety',difficulty:2,q:'Which practice is safest when inserting an indwelling urinary catheter in acute care?',options:['Clean technique with reused equipment','Aseptic technique with sterile equipment by trained personnel','No hand hygiene if gloves are worn','Insertion without indication','Use of tap water as lubricant'],answer:1,rationale:'CDC recommends aseptic insertion with sterile equipment in acute-care hospitals.',source:'CDC_CAUTI'},
{id:122,category:'Infection & Patient Safety',difficulty:2,case:'A nurse removes gloves after wound care. The gloves were visibly contaminated with drainage.',q:'What should the nurse do next?',options:['Skip hand hygiene because gloves were used.','Perform hand hygiene immediately.','Touch the medication cart first.','Put on new gloves without cleaning hands.','Wipe hands on the bed sheet.'],answer:1,rationale:'Gloves do not replace hand hygiene; hands should be cleaned after glove removal.',source:'CDC_STANDARD'},
{id:123,category:'Infection & Patient Safety',difficulty:3,q:'Which combination most strongly suggests a surgical-site infection?',options:['Increasing incisional pain, erythema, warmth and purulent drainage','Gradually decreasing pain with a clean dry incision','Mild stable bruising only','Well-approximated edges without drainage','Normal healing itch alone'],answer:0,rationale:'Increasing local inflammatory signs and purulent drainage are concerning for SSI.',source:'CDC_HAI'},
{id:124,category:'Infection & Patient Safety',difficulty:2,q:'Which statement about healthcare-associated infections is correct?',options:['They occur only in ICUs.','They include infections such as SSI, CAUTI and CLABSI and are an important patient-safety concern.','They are always unavoidable.','Hand hygiene does not affect them.','Only surgical patients can develop them.'],answer:1,rationale:'CDC identifies SSI, CAUTI, CLABSI and other infections as major healthcare-associated infections.',source:'CDC_HAI'},
{id:125,category:'Infection & Patient Safety',difficulty:3,case:'A patient with a fresh abdominal incision asks why the nurse is cleaning hands before examining the wound even though gloves will be worn.',q:'What is the best explanation?',options:['Gloves completely replace hand hygiene.','Hand hygiene before and after patient contact remains important because gloves can become contaminated and are not a substitute for clean hands.','Hand hygiene is only for visibly dirty hands.','It is done only to protect the nurse.','It has no role in preventing infection.'],answer:1,rationale:'Hand hygiene is a fundamental component of Standard Precautions and remains necessary with glove use.',source:'CDC_STANDARD'}
]);
