window.KSA_QUESTIONS.push(...[
{id:19,category:'Bleeding & Shock',difficulty:2,case:'Two hours after abdominal surgery, a patient\'s JP drain suddenly fills with 250 mL of bright-red blood. HR 124, BP 86/50, skin cool and clammy.',q:'What is the priority nursing action?',options:['Empty the drain and wait for the next scheduled vital signs.','Assess ABCs, call for urgent help, support oxygenation/circulation, maintain IV access and notify the surgical team.','Clamp the drain permanently.','Give the patient food and oral fluids.','Ambulate the patient to improve circulation.'],answer:1,rationale:'This presentation strongly suggests active postoperative hemorrhage with shock. Immediate resuscitative assessment and escalation are required.',source:'NCBI_PERIOP'},
{id:20,category:'Bleeding & Shock',difficulty:1,q:'Which combination is most consistent with early hypovolemic shock?',options:['Bradycardia, hypertension, warm dry skin','Tachycardia, falling blood pressure, cool clammy skin and reduced urine output','Hypertension, slow respirations and polyuria','Normal heart rate, flushed skin and increased urine output','Isolated mild nausea with stable vital signs'],answer:1,rationale:'Loss of circulating volume commonly produces tachycardia, hypotension as shock progresses, cool clammy skin and oliguria from reduced perfusion.',source:'NCBI_PERIOP'},
{id:21,category:'Bleeding & Shock',difficulty:3,q:'A postoperative patient with suspected hemorrhage has a hemoglobin result that is not yet significantly decreased. What is the best interpretation?',options:['Acute bleeding is ruled out.','A single early hemoglobin value cannot exclude acute hemorrhage; clinical signs and trends remain critical.','The patient should be discharged.','Only hemoglobin determines whether shock is present.','Bleeding cannot occur if the surgical dressing is dry.'],answer:1,rationale:'In acute hemorrhage, laboratory changes may lag behind clinical deterioration. Vital signs, perfusion, drain output and serial trends are essential.',source:'NCBI_PERIOP'},
{id:22,category:'Bleeding & Shock',difficulty:3,case:'A septic postoperative patient remains hypotensive after initial fluid resuscitation and requires a vasopressor.',q:'Which vasopressor is recommended as first-line in septic shock?',options:['Norepinephrine','Dopamine for every patient','Phenylephrine as universal first-line','Digoxin','Furosemide'],answer:0,rationale:'Surviving Sepsis Campaign guidance recommends norepinephrine as the first-line vasopressor for septic shock.',source:'SCCM_SEPSIS'},
{id:23,category:'Bleeding & Shock',difficulty:3,q:'When caring for a patient in shock, which change most strongly suggests worsening organ perfusion?',options:['Urine output falls and mental status deteriorates.','The patient asks for water.','Temperature decreases from 37.2°C to 37.0°C.','Pain decreases after analgesia.','The patient requests to sleep.'],answer:0,rationale:'Reduced urine output and altered mental status are important signs of inadequate end-organ perfusion.',source:'NCBI_PERIOP'},
{id:24,category:'Respiratory / DVT / PE',difficulty:2,case:'A patient on postoperative day 2 suddenly develops dyspnea, pleuritic chest pain, HR 132 and SpO₂ 84%.',q:'Which complication should be high on the differential?',options:['Pulmonary embolism','Constipation','Urinary retention','Superficial wound irritation','Simple insomnia'],answer:0,rationale:'Sudden dyspnea, tachycardia, hypoxemia and pleuritic chest pain after surgery are classic warning features for pulmonary embolism.',source:'CDC_VTE'},
{id:25,category:'Respiratory / DVT / PE',difficulty:1,q:'Which finding is most characteristic of a possible DVT in one leg?',options:['Bilateral equal coolness without pain','Unilateral swelling, pain/tenderness, warmth and redness','Isolated headache','Dry cough only','Symmetric ankle movement'],answer:1,rationale:'CDC lists unilateral swelling, pain/tenderness, warmth and redness/discoloration among common DVT findings.',source:'CDC_VTE'},
{id:26,category:'Respiratory / DVT / PE',difficulty:2,q:'Which intervention helps reduce postoperative VTE risk in an appropriate patient?',options:['Prolonged immobility','Early mobilization and prescribed mechanical/pharmacologic prophylaxis','Routine dehydration','Massaging a leg with suspected DVT','Keeping knees flexed for long periods'],answer:1,rationale:'Mobilization after surgery and appropriate prophylaxis help reduce healthcare-associated VTE risk.',source:'CDC_VTE'},
{id:27,category:'Respiratory / DVT / PE',difficulty:3,case:'A postoperative patient has sudden severe dyspnea and hypotension. A PE is suspected.',q:'What is the nurse\'s first priority?',options:['Ask the patient to walk to improve circulation.','Assess and support airway/breathing/circulation, administer oxygen as indicated and activate urgent medical response.','Massage the affected calf.','Delay escalation until diagnostic imaging confirms PE.','Offer a large meal.'],answer:1,rationale:'A suspected PE with hypoxemia or hemodynamic instability is an emergency. Stabilization and rapid escalation come before definitive diagnosis.',source:'CDC_VTE'},
{id:28,category:'Respiratory / DVT / PE',difficulty:2,q:'Which postoperative patient has the greatest VTE risk?',options:['Young ambulatory patient after a minor procedure','Patient after major pelvic surgery who remains immobile','Patient with a paper cut','Patient walking independently six times daily after a minor procedure','Patient with seasonal allergies'],answer:1,rationale:'Major surgery and prolonged immobility are important risk factors for DVT/PE.',source:'CDC_VTE'},
{id:29,category:'Respiratory / DVT / PE',difficulty:3,q:'A patient with a suspected DVT asks the nurse to massage the painful calf. What is the best response?',options:['Massage vigorously to break up the clot.','Avoid massaging the limb and promptly notify the clinical team for evaluation.','Apply deep heat and encourage strenuous exercise.','Ignore the symptom until the next shift.','Ask the patient to stand on the affected leg continuously.'],answer:1,rationale:'A suspected DVT requires prompt evaluation; vigorous massage of a potentially thrombosed limb is inappropriate.',source:'CDC_VTE'},
{id:30,category:'Sepsis',difficulty:1,q:'Which statement about sepsis is most accurate?',options:['Sepsis can be ruled out with one normal biomarker.','Sepsis and septic shock are medical emergencies requiring prompt recognition and treatment.','Antibiotics should always wait 24 hours.','Only ICU patients can develop sepsis.','Normal temperature excludes sepsis.'],answer:1,rationale:'Surviving Sepsis Campaign emphasizes that sepsis and septic shock are medical emergencies and treatment/resuscitation should begin promptly.',source:'SCCM_SEPSIS'},
{id:31,category:'Sepsis',difficulty:2,q:'For a patient with suspected sepsis, when should blood cultures ideally be obtained?',options:['Only after 48 hours of antibiotics','As soon as possible and ideally before antimicrobial therapy, if this does not cause harmful delay','Only after discharge','Only if temperature exceeds 40°C','Blood cultures are never useful in sepsis'],answer:1,rationale:'Current Surviving Sepsis guidance recommends collecting blood cultures as soon as possible and ideally before antimicrobials.',source:'SCCM_SEPSIS'},
{id:32,category:'Sepsis',difficulty:3,q:'For adults with sepsis-induced hypoperfusion or septic shock, what initial crystalloid volume does the Surviving Sepsis Campaign suggest within the first 3 hours?',options:['At least 30 mL/kg, individualized with frequent reassessment','Exactly 5 mL/kg for every patient','100 mL total regardless of weight','No IV fluids under any circumstances','At least 100 mL/kg without reassessment'],answer:0,rationale:'Guidance suggests at least 30 mL/kg of IV crystalloid in the first 3 hours, while emphasizing individualization and frequent reassessment.',source:'SCCM_SEPSIS'},
{id:33,category:'Sepsis',difficulty:2,case:'A postoperative patient has T 39.2°C, HR 128, BP 88/54, RR 28, new confusion and purulent wound drainage.',q:'What is the best nursing response?',options:['Wait for the next routine round.','Recognize possible sepsis, assess ABCs/perfusion, escalate urgently, obtain ordered cultures/lactate and support timely antibiotics/fluids.','Give only an antipyretic and reassess tomorrow.','Remove the IV line and stop all monitoring.','Encourage the patient to sleep.'],answer:1,rationale:'This patient has infection plus signs of organ dysfunction/hemodynamic compromise. Prompt sepsis assessment and treatment are required.',source:'SCCM_SEPSIS'},
{id:34,category:'Sepsis',difficulty:3,q:'Which statement about lactate in sepsis is correct?',options:['A normal lactate always excludes sepsis.','Lactate may help assess severity/perfusion but must be interpreted in clinical context.','Lactate is only useful in diabetes.','Lactate should never be repeated.','Lactate directly identifies the causative organism.'],answer:1,rationale:'Lactate is useful as part of assessment/resuscitation, but sepsis remains a clinical diagnosis and lactate must be interpreted in context.',source:'SCCM_SEPSIS'}
]);
