window.KSA_QUESTIONS.push(...[
{id:35,category:'Wounds & Drains',difficulty:1,case:'On postoperative day 6, a patient coughs and the abdominal incision opens with bowel visible.',q:'What is the priority nursing intervention?',options:['Push the bowel back into the abdomen.','Cover the area with a sterile saline-moistened/nonadherent dressing, reduce strain, keep the patient NPO and call the surgeon urgently.','Leave the wound uncovered to dry.','Ask the patient to walk.','Apply a tight abdominal tourniquet.'],answer:1,rationale:'Evisceration is a surgical emergency. Protect exposed tissue with a sterile saline-moistened dressing, reduce tension, keep NPO and urgently notify the surgical team.',source:'NCBI_WOUND'},
{id:36,category:'Wounds & Drains',difficulty:2,q:'Which wound finding is most concerning for surgical-site infection?',options:['Incision edges approximated with minimal discomfort','Redness, warmth, increasing tenderness and purulent drainage','Small stable bruise without pain','Dry intact dressing','Gradually decreasing pain'],answer:1,rationale:'Redness, warmth, tenderness, increased/purulent drainage and fever are common warning signs of surgical-site infection.',source:'NCBI_WOUND'},
{id:37,category:'Wounds & Drains',difficulty:2,q:'Which change in a surgical drain should be reported promptly?',options:['Output gradually decreases as expected.','Sudden large increase in bright-red drainage with tachycardia.','Drain remains secured to the patient.','Small amount of expected serosanguineous fluid.','Output is measured and documented.'],answer:1,rationale:'A sudden increase in bright-red drainage with systemic changes can indicate active bleeding.',source:'NCBI_PERIOP'},
{id:38,category:'Wounds & Drains',difficulty:2,q:'What is a key nursing principle when managing a closed surgical drain?',options:['Measure and document amount and character of drainage.','Disconnect the system routinely to expose it to air.','Never assess the insertion site.','Discard output without measurement.','Clamp the drain continuously unless the patient is sleeping.'],answer:0,rationale:'Drain assessment includes amount, color/character, patency and insertion-site condition; trends can reveal complications.',source:'NCBI_PERIOP'},
{id:39,category:'Wounds & Drains',difficulty:3,case:'A patient with a chest tube becomes acutely dyspneic. The tube is visibly kinked under the bed rail.',q:'What is the best immediate nursing action?',options:['Leave it kinked to prevent air entry.','Relieve the kink, assess the patient and drainage system, provide oxygen as indicated and escalate if distress persists.','Remove the chest tube.','Clamp the chest tube for the rest of the shift.','Ask the patient to walk to radiology alone.'],answer:1,rationale:'A kink can obstruct chest drainage. Restore patency without removing the tube, assess respiratory status and escalate acute deterioration.',source:'NCBI_PERIOP'},
{id:40,category:'Transfusion & Pharmacology',difficulty:1,case:'Fifteen minutes after starting packed red cells, a patient develops chills, dyspnea and back pain.',q:'What is the nurse\'s first action?',options:['Increase the transfusion rate.','Stop the transfusion immediately and assess the patient.','Give food.','Ignore symptoms until the unit finishes.','Discard the blood bag before notifying anyone.'],answer:1,rationale:'A suspected acute transfusion reaction requires immediate interruption of the transfusion and patient assessment.',source:'NHS_TRANSFUSION'},
{id:41,category:'Transfusion & Pharmacology',difficulty:2,q:'After stopping a suspected severe transfusion reaction, which action is appropriate?',options:['Remove all IV access.','Maintain venous access with 0.9% saline using new tubing as required by protocol and notify the medical team/blood bank.','Restart the same blood immediately at a faster rate.','Give intramuscular iron.','Send the patient home.'],answer:1,rationale:'Guidance for severe reactions includes stopping transfusion, maintaining IV access with saline, reassessing vital signs and notifying the relevant teams.',source:'NHS_TRANSFUSION'},
{id:42,category:'Transfusion & Pharmacology',difficulty:1,q:'What medication reverses unfractionated heparin?',options:['Naloxone','Protamine sulfate','Vitamin K','Flumazenil','Atropine'],answer:1,rationale:'Protamine sulfate binds heparin and rapidly reverses its anticoagulant effect.',source:'ACCP_HEPARIN'},
{id:43,category:'Transfusion & Pharmacology',difficulty:1,q:'Which medication is used to reverse opioid effects in clinically significant opioid toxicity?',options:['Naloxone','Protamine','Phytonadione','Calcium gluconate','Furosemide'],answer:0,rationale:'Naloxone is an opioid antagonist used to reverse life-threatening opioid effects such as respiratory depression.',source:'STANDARD_PHARM'},
{id:44,category:'Transfusion & Pharmacology',difficulty:1,q:'Which medication is associated with reversal of warfarin\'s vitamin K antagonist effect?',options:['Vitamin K (phytonadione)','Naloxone','Protamine sulfate only','Flumazenil','Digoxin immune Fab'],answer:0,rationale:'Vitamin K is part of reversal strategies for warfarin/VKA effect, with additional agents such as PCC in major bleeding depending on clinical circumstances.',source:'ACCP_ANTICOAG'},
{id:45,category:'Transfusion & Pharmacology',difficulty:2,q:'Which patient requires the most immediate follow-up after IV opioid administration?',options:['Pain decreased from 8/10 to 4/10; RR 16','RR 8/min with increasing sedation','Mild dry mouth','Patient asks for a blanket','Patient reports pain 5/10 but is alert and breathing normally'],answer:1,rationale:'Bradypnea with increasing sedation may indicate opioid-induced respiratory depression and requires immediate assessment/intervention.',source:'NCBI_PERIOP'},
{id:46,category:'Transfusion & Pharmacology',difficulty:3,q:'A patient receiving IV heparin develops major bleeding. Which information is most relevant when the team calculates protamine dosing?',options:['Amount of heparin received recently and time since administration','Patient\'s favorite food','Last bowel movement only','Hair color','Length of hospital stay only'],answer:0,rationale:'Protamine dosing for UFH reversal depends on the amount of heparin administered recently and its short half-life.',source:'ACCP_HEPARIN'},
{id:47,category:'Transfusion & Pharmacology',difficulty:2,q:'Which practice is safest for a high-alert medication such as insulin or anticoagulants?',options:['Bypass patient identification if you know the patient.','Follow medication rights, verify dose/indication and use an independent double-check when required by institutional policy.','Prepare medications for several patients in unlabeled syringes.','Ignore allergy documentation.','Document before giving the medication regardless of whether it is administered.'],answer:1,rationale:'High-alert medication safety relies on reliable identification, correct order/dose verification and policy-required safeguards.',source:'CDC_STANDARD'},
{id:48,category:'Fluids / Electrolytes / Calculations',difficulty:2,q:'Which postoperative finding is most consistent with clinically significant hypokalemia?',options:['Muscle weakness with possible cardiac rhythm changes','Severe polycythemia','Hyperactive reflexes caused only by high potassium','Bright-red wound drainage','Unilateral calf redness'],answer:0,rationale:'Potassium disturbances can produce muscle weakness and potentially dangerous cardiac rhythm changes.',source:'STANDARD_CLINICAL'},
{id:49,category:'Fluids / Electrolytes / Calculations',difficulty:2,q:'An IV order is 1,000 mL over 8 hours. What pump rate should be programmed?',options:['80 mL/h','100 mL/h','125 mL/h','150 mL/h','200 mL/h'],answer:2,rationale:'1000 ÷ 8 = 125 mL/hour.',source:'CALC'},
{id:50,category:'Fluids / Electrolytes / Calculations',difficulty:2,q:'The prescription is 750 mg. The vial contains 500 mg in 2 mL. How many mL should be administered?',options:['1 mL','2 mL','3 mL','4 mL','5 mL'],answer:2,rationale:'(750 ÷ 500) × 2 mL = 3 mL.',source:'CALC'}
]);
