window.KSA_SOURCES={
KFSHRC_VALUES:{label:"KFSHRC — Vision, Mission and Values",url:"https://services.kfshrc.edu.sa/external/en/home/about/visionmissionvalues"},
KFSHRC_STAFFNURSE:{label:"KFSHRC — Staff Nurse I vacancy/responsibilities",url:"https://services.kfshrc.edu.sa/en/home/careers/vacancies/158582"},
KFSHRC_SURGERY:{label:"KFSHRC Jeddah — Surgery Department",url:"https://services.kfshrc.edu.sa/en/home/hospitals/jeddah/surgeryj"},
WHO_SURGICAL:{label:"WHO — Surgical Safety Checklist",url:"https://www.who.int/teams/integrated-health-services/quality-of-care-and-patient-safety/patient-safety-guidance-and-tools/safe-surgery/tool-and-resources"},
SCCM_SEPSIS:{label:"Surviving Sepsis Campaign — Adult Guidelines",url:"https://sccm.org/survivingsepsiscampaign/guidelines-and-resources/surviving-sepsis-campaign-adult-guidelines"},
CDC_STANDARD:{label:"CDC — Standard Precautions / Infection Control",url:"https://www.cdc.gov/infection-control/hcp/basics/standard-precautions.html"},
CDC_CAUTI:{label:"CDC — CAUTI Prevention Recommendations",url:"https://www.cdc.gov/infection-control/hcp/cauti/summary-of-recommendations.html"},
CDC_HAI:{label:"CDC — Healthcare-Associated Infections",url:"https://www.cdc.gov/healthcare-associated-infections/about/index.html"},
CDC_VTE:{label:"CDC — Venous Thromboembolism (DVT/PE)",url:"https://www.cdc.gov/blood-clots/about/"},
AHRQ_RRT:{label:"AHRQ PSNet — Rapid Response Systems",url:"https://psnet.ahrq.gov/primer/rapid-response-systems"},
NCBI_PERIOP:{label:"NCBI Bookshelf — Perioperative Care & Postoperative Complications",url:"https://www.ncbi.nlm.nih.gov/books/NBK613066/"},
NCBI_WOUND:{label:"NCBI Bookshelf — Wound Dehiscence / Wound Care",url:"https://www.ncbi.nlm.nih.gov/books/NBK551712/"},
NHS_TRANSFUSION:{label:"NHS — Management of suspected transfusion reactions",url:"https://www.rightdecisions.scot.nhs.uk/nhs-borders-clinical-guidelines/acute-services/blood-transfusion/transfusion-policy/"},
ACCP_HEPARIN:{label:"ACCP/PMC — Reversal of unfractionated heparin",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3278070/"},
ACCP_ANTICOAG:{label:"ACCP/PMC — Anticoagulant management and VKA reversal",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3278055/"},
DAILYMED_NALOXONE:{label:"DailyMed — Naloxone hydrochloride injection",url:"https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=21d20dff-6efe-481e-a5a0-9c80ded73ca9"},
DAILYMED_FLUMAZENIL:{label:"DailyMed — Flumazenil injection",url:"https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=a72d9fc1-121c-455d-93a9-002378c9968f"},
DAILYMED_PROTAMINE:{label:"DailyMed — Protamine sulfate injection",url:"https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=c76876da-b9a8-45d0-9278-7df3288d3a06"},
DAILYMED_ENOXAPARIN:{label:"DailyMed — Enoxaparin sodium injection",url:"https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7fa78f8d-92d9-434a-8e26-b886ab0ae77f"},
DAILYMED_WARFARIN:{label:"DailyMed — Warfarin sodium",url:"https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bd6ea120-5d1c-4815-94f2-81e28dc6b7a9"},
ACC_BLEEDING:{label:"ACC — Management of anticoagulant-related bleeding",url:"https://www.acc.org/latest-in-cardiology/ten-points-to-remember/2020/07/10/11/26/2020-acc-expert-consensus-decision-pathway-on-bleeding"},
DAILYMED_PRAXBIND:{label:"DailyMed — Idarucizumab (Praxbind)",url:"https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c7400f8a-dcf4-a6df-6d07-983081b1bf34"},
DAILYMED_ANDEXXA:{label:"DailyMed — Andexanet alfa (Andexxa)",url:"https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2d9d90a6-63e6-46ef-96ff-dd6519ae7b6c"},
DAILYMED_NAC:{label:"DailyMed — Acetylcysteine injection",url:"https://dailymed.nlm.nih.gov/dailymed/lookup.cfm?setid=f811ddfc-d7c1-4637-ae81-80c38a77cb80&version=3"},
DAILYMED_DIGIFAB:{label:"DailyMed — Digoxin immune Fab (DigiFab)",url:"https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c05ee6a5-c98b-45f4-83fd-40781639d653"},
DAILYMED_SUGAMMADEX:{label:"DailyMed — Sugammadex injection",url:"https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55b2eb4e-4d77-c555-e063-6294a90abf9e"},
MHAUS_DANTROLENE:{label:"MHAUS — Malignant hyperthermia treatment / dantrolene",url:"https://www.mhaus.org/healthcare-professionals/mhaus-recommendations/what-evidence-based-interventions-are-recommended-to-alleviate-hyperthermia-associated-with-malignant-hyperthermia/"},
ASRA_LAST:{label:"ASRA — Local Anesthetic Systemic Toxicity checklist",url:"https://asra.com/news-publications/asra-updates/blog-landing/guidelines/2020/11/01/checklist-for-treatment-of-local-anesthetic-systemic-toxicity"},
STANDARD_PHARM:{label:"Core pharmacology review — verify against institutional policy",url:"https://www.ncbi.nlm.nih.gov/books/"},
STANDARD_CLINICAL:{label:"Core adult nursing review — verify against institutional protocol",url:"https://www.ncbi.nlm.nih.gov/books/"},
STANDARD_NURSING:{label:"Core nursing prioritization/delegation review",url:"https://www.ncbi.nlm.nih.gov/books/"},
CALC:{label:"Medication calculation practice — generated for study",url:""},
INTERVIEW:{label:"Behavioral interview practice — STAR structure",url:""}
};
window.KSA_QUESTIONS=[];
